timeout: 0
verbose: yes
serial: yes
default_entry: 1

/ Folkering OS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/initrd.fpk
    cmdline: loglevel=debug
    kaslr: no