#!/usr/bin/env python3
"""Folkering OS `.fbin` writer.

Hosts the build-time bridge from "I have an array of f32s" to "I have
the bytes the inference task can mmap from Synapse VFS". Spec lives
in `userspace/inference/src/weights.rs`.

Today we use it to generate test blobs for the boot self-tests
(D.3.1, D.3.3, ...). When D.3.1.3 lands the real HuggingFace →
`.fbin` converter, it's the same writer with a different front-end.
"""

import struct
import sys
from typing import List, Tuple

MAGIC = b"FBN1"
VERSION = 1
PAGE = 4096

DTYPE_F32 = 0
DTYPE_Q8 = 1
DTYPE_Q4 = 2


def write_fbin(tensors: List[Tuple[str, int, List[int], bytes]]) -> bytes:
    """Pack `(name, dtype, shape, raw_bytes)` tuples into a `.fbin` blob.

    Caller is responsible for raw_bytes being the right length for
    `prod(shape) * elem_size(dtype)`.
    """
    # ── First pass: lay out metadata + data offsets ─────────────────
    metadata = bytearray()
    # We need data_offset for each tensor before we can finalize
    # metadata. Strategy: build metadata with placeholder offsets,
    # measure metadata_len, page-align, then fill offsets in a
    # second pass.
    placeholders = []  # (offset_into_metadata, data_len)
    for name, dtype, shape, raw in tensors:
        name_bytes = name.encode("utf-8")
        metadata += struct.pack("<H", len(name_bytes))
        metadata += name_bytes
        metadata += struct.pack("<BB", dtype, len(shape))
        for d in shape:
            metadata += struct.pack("<I", d)
        # Placeholder for data_offset (8 bytes), data_len (8 bytes).
        offset_ph = len(metadata)
        metadata += struct.pack("<QQ", 0, len(raw))
        placeholders.append((offset_ph, len(raw)))

    # ── Compute data section offsets (page-aligned start) ───────────
    data_section_start = ((16 + len(metadata) + (PAGE - 1)) // PAGE) * PAGE
    cur_data_off = data_section_start
    for (ph_off, raw_len), (_, _, _, raw) in zip(placeholders, tensors):
        struct.pack_into("<QQ", metadata, ph_off, cur_data_off, raw_len)
        cur_data_off += raw_len

    # ── Header ──────────────────────────────────────────────────────
    out = bytearray()
    out += MAGIC
    out += struct.pack("<H", VERSION)
    out += struct.pack("<H", len(tensors))
    out += struct.pack("<Q", len(metadata))
    out += metadata

    # ── Pad to page boundary, then append data ─────────────────────
    while len(out) < data_section_start:
        out.append(0)
    for _, _, _, raw in tensors:
        out += raw

    return bytes(out)


def f32_bytes(values) -> bytes:
    """Pack a flat list of floats to little-endian f32 bytes."""
    return struct.pack(f"<{len(values)}f", *values)


def emit_rust_const(name: str, blob: bytes) -> str:
    """Render a `pub const NAME: &[u8] = &[ ... ];` literal of the
    blob bytes, 16 per row, with a one-line comment header so the
    generated file is easy to diff."""
    lines = [
        "// AUTO-GENERATED by tools/fbin-gen/fbin.py — do not edit by hand.",
        f"// Re-run `python tools/fbin-gen/gen_test_blobs.py` if shapes",
        "// or values change.",
        "",
        f"pub const {name}: &[u8] = &[",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hex_parts = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_parts},")
    lines.append("];")
    return "\n".join(lines) + "\n"
