#!/usr/bin/env python3
"""Regenerate the inference crate's hand-built `.fbin` test blobs.

Runs in the repo root:

    python tools/fbin-gen/gen_test_blobs.py

Writes:
    userspace/inference/src/weights_ffn_blob.rs   — D.3.3 FFN test data
    userspace/inference/src/weights_attn_blob.rs  — D.3.4 attention test data

The D.3.1 blob (TEST_FBIN) was hand-coded for the very first format
verification, before this writer existed; it stays as-is to prove
the parser handles bytes from "any" source.
"""

import math
import os
import sys

# Make the local helper importable when run from repo root.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fbin import write_fbin, f32_bytes, emit_rust_const, DTYPE_F32
from tokb import make_synthetic_tokenizer

REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)


def gen_ffn_blob() -> bytes:
    """D.3.3 FFN test:
       x = [1, 2]   (input vector, hidden_dim=2)

       gate_proj 4×2 = [[1, 0], [0, 1], [1, 1], [1, -1]]   row-major
       up_proj   4×2 = [[1, 0], [0, 1], [0, 1], [1, 0]]
       down_proj 2×4 = [[1, 0, 1, 0], [0, 1, 0, 1]]

    Reference computation (Python, math module):
        gate(x) = [1, 2, 3, -1]
        up(x)   = [1, 2, 2, 1]
        silu(g) ≈ [0.7311, 1.7616, 2.8577, -0.2689]
        gate_silu * up ≈ [0.7311, 3.5232, 5.7155, -0.2689]
        down([h]) = [h0+h2, h1+h3] = [6.4466, 3.2543]
        sum ≈ 9.7009
    """
    x = [1.0, 2.0]
    gate_proj = [
        1.0, 0.0,
        0.0, 1.0,
        1.0, 1.0,
        1.0, -1.0,
    ]
    up_proj = [
        1.0, 0.0,
        0.0, 1.0,
        0.0, 1.0,
        1.0, 0.0,
    ]
    down_proj = [
        1.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 1.0,
    ]
    tensors = [
        ("ffn_input", DTYPE_F32, [2],   f32_bytes(x)),
        ("gate_proj", DTYPE_F32, [4, 2], f32_bytes(gate_proj)),
        ("up_proj",   DTYPE_F32, [4, 2], f32_bytes(up_proj)),
        ("down_proj", DTYPE_F32, [2, 4], f32_bytes(down_proj)),
    ]
    return write_fbin(tensors)


def gen_attn_blob() -> bytes:
    """D.3.4 Attention + RoPE test:

       seq_len = 2, hidden_dim = 2, n_heads = 1, head_dim = 2.

       attn_input [2, 2] = [[1, 0], [0, 1]]
       wq, wk, wo [2, 2] = identity
       wv [2, 2]         = 2 * identity
       rope_cos [2, 1]   = [[1.0],          [cos(1)]]   ≈ [[1.0], [0.5403]]
       rope_sin [2, 1]   = [[0.0],          [sin(1)]]   ≈ [[0.0], [0.8415]]

    RoPE convention: theta_0 = 10000^(-2*0/head_dim) = 1, position p uses
    angle p (radians) → pos 0 is identity, pos 1 rotates by 1 rad.

    Reference math (Python `math` module to verify):

      Q = K = x   (identity Wq, Wk)        = [[1, 0], [0, 1]]
      V = 2 * x  (Wv = 2I)                 = [[2, 0], [0, 2]]

      RoPE:
        Q[0] = K[0] = [1, 0]                  (pos 0 is identity)
        Q[1] = K[1] = (0*cos(1) - 1*sin(1),
                       0*sin(1) + 1*cos(1))
                   ≈ [-0.8415, 0.5403]

      scores = Q @ K.T / sqrt(2):
        s[0,0] = 1.0/√2 ≈ 0.7071
        s[0,1] = (1*-0.8415 + 0*0.5403) / √2 ≈ -0.5950
        s[1,0] = (-0.8415*1 + 0.5403*0) / √2 ≈ -0.5950
        s[1,1] = ((-0.8415)² + 0.5403²) / √2 = 1.0 / √2 ≈ 0.7071

      causal mask:
        s[0] = [0.7071, -inf]
        s[1] = [-0.5950, 0.7071]

      softmax (numerically stable, subtract max):
        row 0: [1.0, 0.0]
        row 1: max = 0.7071;
               exp(-1.3021) ≈ 0.2719, exp(0) = 1.0;
               sum = 1.2719; → [0.2138, 0.7862]

      attn @ V:
        out[0] = [1, 0] @ [[2, 0], [0, 2]] = [2, 0]
        out[1] = [0.2138, 0.7862] @ [[2, 0], [0, 2]]
                                          = [0.4276, 1.5724]

      Wo (identity): out unchanged.

      sum = 2 + 0 + 0.4276 + 1.5724 ≈ 4.0
    """
    x = [
        1.0, 0.0,
        0.0, 1.0,
    ]
    wq = wk = wo = [
        1.0, 0.0,
        0.0, 1.0,
    ]
    wv = [
        2.0, 0.0,
        0.0, 2.0,
    ]
    rope_cos = [
        1.0,                # pos 0
        math.cos(1.0),      # pos 1
    ]
    rope_sin = [
        0.0,
        math.sin(1.0),
    ]
    tensors = [
        ("attn_input", DTYPE_F32, [2, 2], f32_bytes(x)),
        ("wq",         DTYPE_F32, [2, 2], f32_bytes(wq)),
        ("wk",         DTYPE_F32, [2, 2], f32_bytes(wk)),
        ("wv",         DTYPE_F32, [2, 2], f32_bytes(wv)),
        ("wo",         DTYPE_F32, [2, 2], f32_bytes(wo)),
        ("rope_cos",   DTYPE_F32, [2, 1], f32_bytes(rope_cos)),
        ("rope_sin",   DTYPE_F32, [2, 1], f32_bytes(rope_sin)),
    ]
    return write_fbin(tensors)


def main():
    rust_targets = [
        ("weights_ffn_blob.rs",  "TEST_FFN_FBIN",  gen_ffn_blob()),
        ("weights_attn_blob.rs", "TEST_ATTN_FBIN", gen_attn_blob()),
    ]
    for filename, const_name, blob in rust_targets:
        out_path = os.path.join(
            REPO_ROOT, "userspace", "inference", "src", filename
        )
        rust = "//! Auto-generated by `tools/fbin-gen/gen_test_blobs.py`.\n"
        rust += "//! Source spec is in that script — keep them in sync.\n\n"
        rust += emit_rust_const(const_name, blob)
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(rust)
        print(f"wrote {out_path}  ({len(blob)} bytes)")

    # Also drop the union of the test tensors as a real on-disk
    # `.fbin` so the OS-side VFS-read path (D.3.1.2) has something
    # to chew on at boot. We write to boot/iso_root/ which folk-pack
    # picks up via `--add model_test.fbin:data:...` in nightly.sh
    # and the dev pack invocation. Keeping the file alongside
    # kernel.elf and initrd.fpk makes it visible in `qm config`-style
    # ops and easy to swap out for real model weights later.
    binary_targets = [
        ("model_test.fbin", gen_combined_blob()),
        # D.3.1 synthetic tokenizer: 256 byte tokens + 3 test merges.
        # Real Qwen tokenizer.json conversion lands in D.3.1.b.
        ("tokenizer_test.tokb", make_synthetic_tokenizer()),
    ]
    for filename, blob in binary_targets:
        out_path = os.path.join(REPO_ROOT, "boot", "iso_root", filename)
        with open(out_path, "wb") as f:
            f.write(blob)
        print(f"wrote {out_path}  ({len(blob)} bytes)")


def gen_combined_blob() -> bytes:
    """A single `.fbin` carrying both the FFN and attention test
    tensors, plus a marker tensor so the VFS-read self-test has
    something tiny to verify before walking the full set.

    The boot self-tests in `inference/src/main.rs` read this via
    `synapse::read_file_shmem("model_test.fbin")` — same parser, same
    correctness checks, just sourced from the real on-disk pipeline.
    Eventually this binary gets replaced by a real Qwen2.5-0.5B
    converted from HuggingFace safetensors (D.3.1.3).
    """
    import math as _math

    # Marker: a 4-element identity vector so VFS readers can sanity-
    # check before the heavy tensors. The hash will print at boot
    # the same way our other tensors do, providing a fingerprint
    # that drifts if the file gets corrupted in transit.
    marker = [0.1, 0.2, 0.3, 0.4]

    tensors = [
        ("vfs_marker", DTYPE_F32, [4],    f32_bytes(marker)),
        # FFN tensors (same as gen_ffn_blob, kept verbatim for
        # boot-self-test parity).
        ("ffn_input", DTYPE_F32, [2],    f32_bytes([1.0, 2.0])),
        ("gate_proj", DTYPE_F32, [4, 2], f32_bytes([
            1.0, 0.0,  0.0, 1.0,  1.0, 1.0,  1.0, -1.0,
        ])),
        ("up_proj",   DTYPE_F32, [4, 2], f32_bytes([
            1.0, 0.0,  0.0, 1.0,  0.0, 1.0,  1.0, 0.0,
        ])),
        ("down_proj", DTYPE_F32, [2, 4], f32_bytes([
            1.0, 0.0, 1.0, 0.0,  0.0, 1.0, 0.0, 1.0,
        ])),
        # Attention tensors (same as gen_attn_blob).
        ("attn_input", DTYPE_F32, [2, 2], f32_bytes([1.0, 0.0, 0.0, 1.0])),
        ("wq",         DTYPE_F32, [2, 2], f32_bytes([1.0, 0.0, 0.0, 1.0])),
        ("wk",         DTYPE_F32, [2, 2], f32_bytes([1.0, 0.0, 0.0, 1.0])),
        ("wv",         DTYPE_F32, [2, 2], f32_bytes([2.0, 0.0, 0.0, 2.0])),
        ("wo",         DTYPE_F32, [2, 2], f32_bytes([1.0, 0.0, 0.0, 1.0])),
        ("rope_cos",   DTYPE_F32, [2, 1], f32_bytes([1.0, _math.cos(1.0)])),
        ("rope_sin",   DTYPE_F32, [2, 1], f32_bytes([0.0, _math.sin(1.0)])),
    ]
    return write_fbin(tensors)


if __name__ == "__main__":
    main()
