#!/usr/bin/env python3
"""Regenerate the inference crate's hand-built `.fbin` test blobs.

Runs in the repo root:

    python tools/fbin-gen/gen_test_blobs.py

Writes:
    userspace/inference/src/weights_ffn_blob.rs   — D.3.3 FFN test data

The D.3.1 blob (TEST_FBIN) was hand-coded for the very first format
verification, before this writer existed; it stays as-is to prove
the parser handles bytes from "any" source.
"""

import os
import sys

# Make the local helper importable when run from repo root.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fbin import write_fbin, f32_bytes, emit_rust_const, DTYPE_F32

REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)


def gen_ffn_blob() -> bytes:
    """D.3.3 FFN test:
       x = [1, 2]   (input vector, hidden_dim=2)

       gate_proj 4×2 = [[1, 0], [0, 1], [1, 1], [1, -1]]   row-major
       up_proj   4×2 = [[1, 0], [0, 1], [0, 1], [1, 0]]
       down_proj 2×4 = [[1, 0, 1, 0], [0, 1, 0, 1]]

    Reference computation (Python, math module):
        gate(x) = [1, 2, 3, -1]
        up(x)   = [1, 2, 2, 1]
        silu(g) ≈ [0.7311, 1.7616, 2.8577, -0.2689]
        gate_silu * up ≈ [0.7311, 3.5232, 5.7155, -0.2689]
        down([h]) = [h0+h2, h1+h3] = [6.4466, 3.2543]
        sum ≈ 9.7009
    """
    x = [1.0, 2.0]
    gate_proj = [
        1.0, 0.0,
        0.0, 1.0,
        1.0, 1.0,
        1.0, -1.0,
    ]
    up_proj = [
        1.0, 0.0,
        0.0, 1.0,
        0.0, 1.0,
        1.0, 0.0,
    ]
    down_proj = [
        1.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 1.0,
    ]
    tensors = [
        ("ffn_input", DTYPE_F32, [2],   f32_bytes(x)),
        ("gate_proj", DTYPE_F32, [4, 2], f32_bytes(gate_proj)),
        ("up_proj",   DTYPE_F32, [4, 2], f32_bytes(up_proj)),
        ("down_proj", DTYPE_F32, [2, 4], f32_bytes(down_proj)),
    ]
    return write_fbin(tensors)


def main():
    blob = gen_ffn_blob()
    out_path = os.path.join(
        REPO_ROOT, "userspace", "inference", "src", "weights_ffn_blob.rs"
    )
    rust = "//! Auto-generated by `tools/fbin-gen/gen_test_blobs.py`.\n"
    rust += "//! Source spec is in that script — keep them in sync.\n\n"
    rust += emit_rust_const("TEST_FFN_FBIN", blob)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(rust)
    print(f"wrote {out_path}  ({len(blob)} bytes)")


if __name__ == "__main__":
    main()
