//! Peephole optimizer — post-emit pass that scans the encoder buffer
//! for redundant instruction patterns and replaces them with NOPs.
//! Runs after lowering, before `finish()`, so the JIT gets smaller
//! and faster code without changing the lowerer's emission logic.
//!
//! Patterns eliminated:
//!
//! 1. **Self-MOV** — `ADD Xd, XZR, Xd` (canonical A64 register move
//!    where source == dest). Generated by the lowerer when a call
//!    result already sits in X0 or a local.get targets the same
//!    register as the source. Cost: 0 work, 4 wasted bytes.
//!
//! 2. **Self-AND** — `AND Wd, Wd, Wd` where Rd == Rn == Rm. Used
//!    by the lowerer to clear the upper 32 bits of an X register
//!    after an i32 operation, but redundant when the previous
//!    instruction already produced a 32-bit-clean W-result (all
//!    W-form instructions zero-extend to the hosting X by ISA
//!    guarantee). Currently we NOP them conservatively (any
//!    self-AND) — a future pass could check the preceding
//!    instruction for W-form to be more precise.
//!
//! Replaced instructions become NOP (0xD503201F). A separate
//! compaction pass could then slide code down to close the gaps,
//! but for now the NOPs don't hurt — they execute in zero cycles
//! on Cortex-A76's decode stage.

use alloc::vec::Vec;

/// NOP encoding on AArch64.
const NOP: u32 = 0xD503_201F;

/// Run the peephole optimizer over a mutable instruction buffer.
/// Each entry is a 32-bit A64 word in native (little-endian) order.
/// Returns the count of instructions replaced with NOPs.
pub fn optimize(buf: &mut [u8]) -> usize {
    if buf.len() < 4 {
        return 0;
    }
    let n_words = buf.len() / 4;
    let mut eliminated = 0;

    for i in 0..n_words {
        let off = i * 4;
        let word = u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]]);

        // Pattern 1: ADD Xd, XZR, Xd (self-MOV)
        // Encoding: 0x8B1F0000 | (Rd << 16) | (31 << 5) | Rd
        //   = 0x8B00_03E0 | Rd | (Rd << 16)  — but ZR is reg 31
        // Actually ADD Xd, XZR, Xn: 0x8B000000 | (Xn << 16) | (ZR << 5) | Xd
        //   ZR = 31, so (31 << 5) = 0x3E0
        // For self: Xn == Xd, so word = 0x8B0003E0 | Rd | (Rd << 16)
        if is_self_add_x(word) {
            patch_nop(buf, off);
            eliminated += 1;
            continue;
        }

        // Pattern 2: AND Wd, Wd, Wd (self-AND)
        // Encoding: 0x0A000000 | (Rm << 16) | (Rn << 5) | Rd
        // For self: Rd == Rn == Rm
        if is_self_and_w(word) {
            patch_nop(buf, off);
            eliminated += 1;
            continue;
        }
    }

    eliminated
}

/// Check if `word` is `ADD Xd, XZR, Xd` (64-bit ADD with source==dest,
/// second source = register 31 which reads as zero).
fn is_self_add_x(word: u32) -> bool {
    // ADD X (sf=1): top bits = 0x8B (1000_1011)
    // Shift type = LSL #0: bits 23:22 = 00, bits 15:10 = 000000
    // Rm = bits 20:16, Rn = bits 9:5, Rd = bits 4:0
    // For self-MOV: Rn = 31 (ZR), Rm == Rd
    if word & 0xFF_E0_FC_00 != 0x8B_00_00_00 {
        return false; // not ADD X with shift=0
    }
    let rd = word & 0x1F;
    let rn = (word >> 5) & 0x1F;
    let rm = (word >> 16) & 0x1F;
    rn == 31 && rm == rd
}

/// Check if `word` is `AND Wd, Wd, Wd` (32-bit AND with all three
/// regs the same — logically a no-op that just re-writes the same bits).
fn is_self_and_w(word: u32) -> bool {
    // AND W (sf=0): top bits = 0x0A (0000_1010)
    if word & 0xFF_E0_FC_00 != 0x0A_00_00_00 {
        return false;
    }
    let rd = word & 0x1F;
    let rn = (word >> 5) & 0x1F;
    let rm = (word >> 16) & 0x1F;
    rd == rn && rn == rm
}

fn patch_nop(buf: &mut [u8], off: usize) {
    let bytes = NOP.to_le_bytes();
    buf[off..off + 4].copy_from_slice(&bytes);
}

/// Count NOPs in the buffer (useful for metrics).
pub fn count_nops(buf: &[u8]) -> usize {
    let n_words = buf.len() / 4;
    (0..n_words)
        .filter(|&i| {
            let off = i * 4;
            u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]]) == NOP
        })
        .count()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn word_to_bytes(word: u32) -> [u8; 4] {
        word.to_le_bytes()
    }

    #[test]
    fn self_add_x0_eliminated() {
        // ADD X0, XZR, X0 = 0x8B0003E0
        let word = 0x8B00_03E0u32;
        assert!(is_self_add_x(word));
        let mut buf = word_to_bytes(word).to_vec();
        assert_eq!(optimize(&mut buf), 1);
        assert_eq!(
            u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]),
            NOP
        );
    }

    #[test]
    fn non_self_add_preserved() {
        // ADD X1, XZR, X0 — Rd=1, Rm=0 (different)
        let word = 0x8B00_03E1u32;
        assert!(!is_self_add_x(word));
        let mut buf = word_to_bytes(word).to_vec();
        assert_eq!(optimize(&mut buf), 0);
    }

    #[test]
    fn self_and_w0_eliminated() {
        // AND W0, W0, W0 = 0x0A000000
        let word = 0x0A00_0000u32;
        assert!(is_self_and_w(word));
        let mut buf = word_to_bytes(word).to_vec();
        assert_eq!(optimize(&mut buf), 1);
    }

    #[test]
    fn non_self_and_preserved() {
        // AND W0, W1, W0 — Rn=1 != Rd=0
        let word = 0x0A00_0020u32;
        assert!(!is_self_and_w(word));
    }

    #[test]
    fn mixed_buffer() {
        let mut buf = Vec::new();
        // ADD X3, XZR, X3 (self-MOV) → NOP
        buf.extend_from_slice(&(0x8B03_03E3u32).to_le_bytes());
        // MOVZ X0, #42 (not a self-MOV) → kept
        buf.extend_from_slice(&(0xD280_0540u32).to_le_bytes());
        // AND W5, W5, W5 (self-AND) → NOP
        let and_w5 = 0x0A05_00A5u32;
        buf.extend_from_slice(&and_w5.to_le_bytes());
        assert_eq!(optimize(&mut buf), 2);
        // First word → NOP
        assert_eq!(
            u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]),
            NOP
        );
        // Second word → preserved
        assert_eq!(
            u32::from_le_bytes([buf[4], buf[5], buf[6], buf[7]]),
            0xD280_0540
        );
        // Third word → NOP
        assert_eq!(
            u32::from_le_bytes([buf[8], buf[9], buf[10], buf[11]]),
            NOP
        );
    }
}
